# Generated by Django 4.2.2 on 2023-06-21 13:43

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailvideos.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('Heading', wagtail.blocks.CharBlock(form_classname='title', max_length=128)), ('Text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('carousel', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('video', wagtail.embeds.blocks.EmbedBlock())])), ('videodwnld', wagtailvideos.blocks.VideoChooserBlock())], use_json_field=True),
        ),
    ]
