# Generated by Django 4.2.2 on 2023-06-22 11:33

from django.db import migrations, models
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailvideos.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='title1',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('Heading', wagtail.blocks.CharBlock(form_classname='title', max_length=128)), ('Text', wagtail.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('carousel', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock(required=False))])), ('videodwnld', wagtailvideos.blocks.VideoChooserBlock(required=False))], use_json_field=True),
        ),
    ]
