# Generated by Django 4.2.2 on 2023-06-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postpage_title1_alter_postpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpage',
            old_name='title1',
            new_name='subtitle',
        ),
    ]
