# Generated by Django 4.2.2 on 2023-06-24 08:25

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_newscategory'),
        ('post', '0006_rename_title1_postpage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='snippets.newscategory'),
        ),
    ]
